/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientpoolthreads;

import ProtocoleLUGAP.ReponseLUGAP;
import ProtocoleLUGAP.RequeteLUGAP;
import java.awt.Frame;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Philippe
 */
public class LugagesFrame extends javax.swing.JFrame {
    private final int IdVol;
    private final String NomCompagnie;
    private final String Destination;
    private final String HeureDepart;
    private final Frame FenAuthentification;
    private final Client Client;
    
    /**
     * Creates new form LugagesFrame
     */
    LugagesFrame(Frame FenAuthentification, Client Client, int IdVol, String NomCompagnie, String Destination, String HeureDepart) {   
        this.IdVol = IdVol;
        this.NomCompagnie = NomCompagnie;
        this.Destination = Destination;
        this.HeureDepart = HeureDepart;
        this.FenAuthentification = FenAuthentification;
        this.Client = Client;
        
        setTitle("Bagages de : " + this.toString());     
        setLocationRelativeTo(null);           
        initComponents();
        initTableauBagages();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBagages = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTableBagages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identifiant", "Poids", "Type", "Réceptionné (O/N)", "Chargé en soute (O/N)", "Vérifié par la douane (O/N)", "Remarques"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableBagages);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initTableauBagages() {
        HashMap <String, Object> hm = new HashMap<>();
        RequeteLUGAP Req = new RequeteLUGAP(RequeteLUGAP.REQUEST_LOAD_LUGAGES);
        DefaultTableModel dtm = (DefaultTableModel) jTableBagages.getModel();
        
        hm.put("IdVol", getIdVol());
        hm.put("NomCompagnie", getNomCompagnie());
        hm.put("Destination", getDestination());
        hm.put("HureDepart", getHeureDepart());        
        Req.setChargeUtile(hm);
        
        getClient().EnvoyerRequete(Req);       
        //ReponseLUGAP Rep = getClient().RecevoirReponse();
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        boolean Fini = true;//false;
        
        if (Fini)
        {
            Client.Deconnexion();
            FenAuthentification.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    public int getIdVol() {
        return IdVol;
    }

    public String getNomCompagnie() {
        return NomCompagnie;
    }

    public String getDestination() {
        return Destination;
    }

    public String getHeureDepart() {
        return HeureDepart;
    }

    public Frame getFenAuthentification() {
        return FenAuthentification;
    }

    public Client getClient() {
        return Client;
    }
    
    @Override
    public String toString()
    {
        return "VOL " + getIdVol() + " " + getNomCompagnie() + " - " + getDestination() + " " + getHeureDepart();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBagages;
    // End of variables declaration//GEN-END:variables
}
