/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientpoolthreads;

import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Philippe
 */
public class LugagesFrame extends javax.swing.JFrame {
    private final int IdVol;
    private final String NomCompagnie;
    private final String Destination;
    private final String HeureDepart;
    
    /**
     * Creates new form LugagesFrame
     */
    LugagesFrame(int IdVol, String NomCompagnie, String Destination, String HeureDepart) {   
        this.IdVol = IdVol;
        this.NomCompagnie = NomCompagnie;
        this.Destination = Destination;
        this.HeureDepart = HeureDepart;
        
        setTitle("Bagages de : " + this.toString());     
        setLocationRelativeTo(null);           
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getIdVol() {
        return IdVol;
    }

    public String getNomCompagnie() {
        return NomCompagnie;
    }

    public String getDestination() {
        return Destination;
    }

    public String getHeureDepart() {
        return HeureDepart;
    }
  
    @Override
    public String toString()
    {
        return "VOL " + getIdVol() + " " + getNomCompagnie() + " - " + getDestination() + " " + getHeureDepart();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
