package abstracts;

import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.table.DefaultTableModel;
import interfaces.ConsoleServeur;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;

/**
 *
 * @author Philippe
 */
public abstract class AFenApplicationServeur extends javax.swing.JFrame implements ConsoleServeur {
    protected Properties Properties;
    protected final String NomFichierProperties;
    protected int Status;
    /**
     * Creates new form FenApplicationServeur
     */
    public AFenApplicationServeur() {
        initComponents();
        setLocationRelativeTo(null); 
        TraceEvenements("Serveur#Initialisation#Thread Serveur");
        this.Status = STOPPED;
        this.NomFichierProperties = System.getProperty("user.dir").split("/dist")[0] + System.getProperty("file.separator")+ "src" + System.getProperty("file.separator") + this.getClass().getPackage().getName()+ System.getProperty("file.separator") + "config.properties";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButtonStartStop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableauEvenements = new javax.swing.JTable();
        jButtonClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Application_Bagages - Serveur");
        setResizable(false);

        jButtonStartStop.setText("Start");
        jButtonStartStop.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonStartStopActionPerformed(evt);
            }
        });

        TableauEvenements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Origine", "Requête", "Thread"
            }
        ));
        jScrollPane1.setViewportView(TableauEvenements);

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jButtonStartStop)
                .addGap(18, 18, 18)
                .addComponent(jButtonClear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStartStop)
                    .addComponent(jButtonClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartStopActionPerformed
        if (Status == STOPPED) 
        {
            Start();

            jButtonStartStop.setText("Stop");
            Status = RUNNING;
            TraceEvenements("Serveur#Start#Thread Serveur");
            
        }
        else 
        {       
            Stop();            
            TraceEvenements("Serveur#Arrêt du serveur#Thread Serveur");
            jButtonStartStop.setText("Start");
            Status = STOPPED;
        }
    }//GEN-LAST:event_jButtonStartStopActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonClearActionPerformed
    {//GEN-HEADEREND:event_jButtonClearActionPerformed
        ((DefaultTableModel) TableauEvenements.getModel()).setRowCount(0);
    }//GEN-LAST:event_jButtonClearActionPerformed

    protected abstract void Start();
    protected abstract void Stop();
    
    protected abstract void CreerProperties();
    protected void LireProperties()
    {
        FileInputStream fis = null;
        setProperties(new Properties());
        
        try 
        {
            fis = new FileInputStream(NomFichierProperties);
            getProperties().load(fis);
            fis.close();
        } 
        catch (FileNotFoundException ex) 
        {
            CreerProperties();
        }
        catch (IOException ex)
        {
            TraceEvenements("Serveur#Problème avec les properties#Thread Serveur");
        }
    }
    
    @Override
    public void TraceEvenements(String log) {
        ArrayList<String> Ligne = new ArrayList<>();
        StringTokenizer parser = new StringTokenizer(log, "#");
        
        while(parser.hasMoreTokens()){ 
            String Token = parser.nextToken();
            if (Token != null)
                Ligne.add(Token);  
        }
        
        DefaultTableModel dtm = (DefaultTableModel) TableauEvenements.getModel();        
        dtm.insertRow(dtm.getRowCount(), Ligne.toArray());
        
        TableauEvenements.setModel(dtm);
    }

    public Properties getProperties()
    {
        return Properties;
    }

    public void setProperties(Properties Properties)
    {
        this.Properties = Properties;
    }

    public int getStatus()
    {
        return Status;
    }

    public void setStatus(int Status)
    {
        this.Status = Status;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTable TableauEvenements;
    protected javax.swing.JButton jButtonClear;
    protected javax.swing.JButton jButtonStartStop;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
