package serveurbagages;

import abstract_classes.AFenApplicationServeur;
import abstract_classes.AThreadServeur;
import abstract_classes.ThreadServeurMultiClients;
import impl.ListeTaches;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Philippe
 */
public class FenApplicationServeurBagages extends AFenApplicationServeur
{
    private int Port_Bagages, Port_CheckIn;
    private AThreadServeur TS_Bagages, TS_CheckIn;
    /**
     * Creates new form FenApplicationServeurBagages
     */
    public FenApplicationServeurBagages()
    {
        //super();  
        this.jButtonStartStop.doClick();
        Port_Bagages = Integer.parseInt(Properties.get("PORT_BAGAGES").toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void Start()
    {        
        ThreadServeurMultiClients ts = new ThreadServeurMultiClients(Port_Bagages, this, new ListeTaches(), Properties);
        TS_Bagages = ts;
        ts.start();
    }

    @Override
    protected void Stop()
    {
        TS_Bagages.interrupt();
        try
        {
            TS_Bagages.getSSocket().close();
        }
        catch (IOException ex)
        {
            Logger.getLogger(FenApplicationServeurBagages.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) 
    {
        try
        {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FenApplicationServeurBagages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FenApplicationServeurBagages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FenApplicationServeurBagages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FenApplicationServeurBagages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

            /* Create and display the form */
           java.awt.EventQueue.invokeLater(new Runnable() {
                   @Override
                   public void run() {
                        FenApplicationServeurBagages Serveur = new FenApplicationServeurBagages();
                        Serveur.setVisible(true);
                   }
           });
        }
        catch(Exception e)
        {
            System.out.println("e = " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
