/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientmutlithreadtickmap;

import cryptographie.CleSecrete;
import cryptographie.KeyStoreUtils;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.security.cert.X509Certificate;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.SecretKey;
import javax.swing.JOptionPane;

/**
 *
 * @author Doublon
 */
public class ClientInformationGUI extends javax.swing.JFrame
{
    private static String keyStorePath = System.getProperty("user.dir")+ System.getProperty("file.separator")+"keystore"+System.getProperty("file.separator")+"ClientKeystore.jks";
    private static String keyStoreDirPath = System.getProperty("user.dir")+ System.getProperty("file.separator")+"keystore"+System.getProperty("file.separator");
    private static String keySecretHmac = "CleSecreteHMACClient.ser";
    private static String keyStorePsw = "123Soleil";
    private static String aliasKeyStrore="clientprivatekey";
    
    private Client client;
    private HashMap<String, Object> Vols;
    private KeyStoreUtils ks;
    private X509Certificate certifServeur;
    private SecretKey cleSecrete;

    /**
     * Creates new form ClientInformationGUI
     */
    public ClientInformationGUI(Client c , HashMap<String, Object> Vols)
    {
        setClient(c);
        setVols(Vols);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelAccompagnant = new javax.swing.JLabel();
        jButtonEnregistrer = new javax.swing.JButton();
        jButtonEffacer = new javax.swing.JButton();
        jTextFieldAccompagnant = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNom.setText("Nom :");

        jLabelPrenom.setText("Prenom :");

        jLabelAccompagnant.setText("Nombre d'accompagnant :");

        jButtonEnregistrer.setText("Enregistrer");
        jButtonEnregistrer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonEnregistrerActionPerformed(evt);
            }
        });

        jButtonEffacer.setText("Effacer");

        jTextFieldAccompagnant.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNom)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNom))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAccompagnant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAccompagnant, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPrenom)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPrenom))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButtonEnregistrer)
                        .addGap(47, 47, 47)
                        .addComponent(jButtonEffacer)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenom)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAccompagnant)
                    .addComponent(jTextFieldAccompagnant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnregistrer)
                    .addComponent(jButtonEffacer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnregistrerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonEnregistrerActionPerformed
    {//GEN-HEADEREND:event_jButtonEnregistrerActionPerformed
        if(jTextFieldNom.getText().isEmpty() || jTextFieldPrenom.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Vous devez remplir les champs", "Erreur", JOptionPane.ERROR_MESSAGE);
        else
        {
            ClientBD clientbd = new ClientBD(jTextFieldNom.getText(),jTextFieldPrenom.getText(),Integer.parseInt(jTextFieldAccompagnant.getText()));
            CrypteVol(keyStoreDirPath,keySecretHmac);
        }
    
    }//GEN-LAST:event_jButtonEnregistrerActionPerformed

    public void CrypteVol(String path, String nameFile)
    {
        int idVol = (int) getVols().get("IdVol");
        
        File f = new File(path+nameFile);
        if(f.exists())
        {
            try
            {
                ObjectInputStream cleFichier =new ObjectInputStream(new FileInputStream(path+nameFile));
                SecretKey keyLoad=(SecretKey) cleFichier.readObject();
                cleFichier.close();
                cleSecrete=(SecretKey) new CleSecrete(keyLoad);
            } catch (IOException ex)
            {
                Logger.getLogger(AuthentificationGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex)
            {
                Logger.getLogger(AuthentificationGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ClientInformationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ClientInformationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ClientInformationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ClientInformationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ClientInformationGUI(null,null).setVisible(true);
            }
        });
    }

    public Client getClient()
    {
        return client;
    }

    public void setClient(Client client)
    {
        this.client = client;
    }

    public HashMap<String, Object> getVols()
    {
        return Vols;
    }

    public void setVols(HashMap<String, Object> Vols)
    {
        this.Vols = Vols;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEffacer;
    private javax.swing.JButton jButtonEnregistrer;
    private javax.swing.JLabel jLabelAccompagnant;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JTextField jTextFieldAccompagnant;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    // End of variables declaration//GEN-END:variables
}
